### ISSUE TITLE
Use t.Helper for assertions

### ISSUE THREAD

**Issue by dnephin** [gotestyourself/gotestyourself#20]
https://golang.org/pkg/testing/#T.Helper

This was added in GO 1.9, so we should probably wait a little bit to add it.

**Comment by vdemeester** [comment]
@dnephin we could also use build tags to enable it only for go 1.9 (but this might be tricky or ugly to do though)

**Comment by dnephin** [comment]
This is fixed in #34 using

```go
if ht, ok := t.t.(helperT); ok {
    ht.Helper()
}
```
