### ISSUE TITLE
Better assertions

### ISSUE THREAD

**Issue by dnephin** [gotestyourself/gotestyourself#26]
Currently the recommendation is to use testify. Testify does a lot of things well:
* failures report the line that caused the error (not the helper)
* custom messages can be added to the default error message
* comparison of complex types includes a diff using difflib

However there are some limitations:
* the multiline diffs from difflib show every pointer as being different because of the address 
* there's no way to ignore some fields on structs that may always be different (ex: timestamps)
* comparisons can fail because of unexported internal fields
* there are a bunch of unnecessary assertions on the interface, yet they are slow to add (or even respond to PRs to add) necessary ones (https://github.com/stretchr/testify/pull/486)

Many of the issues may be fixed by using https://godoc.org/github.com/google/go-cmp/cmp

It might be worth it to add an `assert` library that has all the good parts of the testify library, with some or all of these improvements.

**Comment by dnephin** [comment]
An interesting test case: https://github.com/stretchr/testify/issues/520

**Comment by fJancsoSzabo** [comment]
@dnephin My issue ([https://github.com/stretchr/testify/issues/520](https://github.com/stretchr/testify/issues/520)) is inaccurate, I was using 1.1.4, the bug has been fixed in master.

**Comment by dnephin** [comment]
Ok, either way I think it's an interesting test case for an assertion library. I'm glad it was fixed in testify/assert.
