### ISSUE TITLE
Proposal: use gotest.tools vanity url

### ISSUE THREAD

**Issue by dnephin** [gotestyourself/gotestyourself#77]
The current import url is quite long (`github.com/gotestyourself/gotestyourself/pkg`). I've setup a vanity url server at https://gotest.tools. 

I propose we make the following changes:
* add canonical import comments to the packages `// import gotest.tools/pkg`
* change internal imports to use the vanity url
* move the git repo to `github.com/gotestyourself/gotest.tools`

**Comment by vdemeester** [comment]
@dnephin would it be for a `v2` — i.e., starting from v2, use the vanity url ? Other than that, sounds ok for me 👼

**Comment by dnephin** [comment]
I was thinking about that as well. I'm not sure, but I can see the argument for doing it as a v2.

**Comment by leonklingele** [comment]
Did this just break all `github.com/gotestyourself/gotestyourself` imports? Why enforce the new vanity URL instead of making it optional?

**Comment by dnephin** [comment]
Nothing should be broken as long as dependencies are checked into `vendor/`, or dependencies are retrieved using a package manager that understands semvar. 

It's necessary to enforce the vanity url because there are cross-package imports (ex: `golden` imports `assert`). If you don't enforce the vanity url then you end up with duplicate copies of the package.
